### ISSUE TITLE
Possibly broken submodule commit

### ISSUE THREAD

**Issue by Min1123** [Wren6991/Hazard3#13]
`fatal: Fetched in submodule path 'test/sim/riscv-compliance/riscv-arch-test', but it did not contain 099a70167993378fe25fe1e668207fc4ea3c0fb0. Direct fetching of that commit failed.`

Looks like the submodule may need a new commit.

**Comment by Wren6991** [comment]
Thanks, I forgot to push a submodule commit that I tagged, should now be fixed.
