### ISSUE TITLE
Transistor count

### ISSUE THREAD

**Issue by ris-work** [Wren6991/Hazard3#18]
Hey,
Thanks for the amazing work.
I haven't found any other appropriate place to ask this and I have absolutely no idea how the fabrication works. How many transistors, approximately, does Hazard3 core in RPi Pico 2 have?

Thanks.
Regards,
Rishikeshan.

**Comment by Wren6991** [comment]
This is my private GitHub; I can't answer any questions about Raspberry Pi's chips here. I also can't make any direct comparisons to Arm processors, as an employee of an Arm licensee.

If you're interested in poking around, you can start by building one of the example FPGA SoCs and playing with the feature set.
