### ISSUE TITLE
Is there a compressed variant of the lb instruction?

### ISSUE THREAD

**Issue by technoblogy** [Wren6991/Hazard3#24]
I'm trying to find the instruction format for the compressed 16-bit version of the **lb** instruction.

Under the documentation for the **lb** instruction in the RP2350 Datasheet (p. 241) it says:

> Compressible if: rd and rs1 are in x8 through x15, and immediate is in the range 0x0 through 0x3.

The referenced document: [Code Size Reduction extensions frozen v1.0.3-1](https://github.com/riscv/riscv-code-size-reduction/releases/download/v1.0.3-1/Zc-v1.0.3-1.pdf) mentions **lbu**, **lh**, and **lhu**, but not **lb**.

Also, I can't find it in your file `hdl/rv_opcodes.vh`. Any suggestions?

Thanks, David

**Comment by Wren6991** [comment]
Nope, just unsigned byte load in Zcb. If you go back through https://lists.riscv.org/g/tech-code-size then you may be able to find the original discussion -- I suspect signed byte loads did not have enough static frequency to make the cut.

For example this old message: https://lists.riscv.org/g/tech-code-size/message/641?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3Arecentpostdate%2Fsticky%2C%2Clb%2C20%2C2%2C0%2C80008826

> The instruction counts are also very interesting. For example, so far I’ve failed to find much use for possible C.LH/C.LB instructions, whereas I’ve found lots of use for the unsigned versions C.LHU/C.LBU (which we have already implemented on silicon). Debian agrees with this finding:
>
> 170158 lbu (~38x more than lb)
>
>   24027 lhu (~7x more than lh)
>
>   4445 lb
>
>   3678 lh

**Comment by Wren6991** [comment]
(The compressibility condition in the RP2350 datasheet is incorrect, and is now removed)

**Comment by technoblogy** [comment]
Thanks for the reply! I thought it was most likely a documentation issue.

> so far I’ve failed to find much use for possible C.LH/C.LB instructions

Yes, I can't imagine why you would want to sign-extend a single byte or halfword.

**Comment by technoblogy** [comment]
In case you're interested, this is why I was exploring your RISC-V extensions in the RP2350:

[Lisp RISC-V assembler RP2350 extensions](http://www.ulisp.com/show?4Y5E)
