### ISSUE TITLE
Register file address width

### ISSUE THREAD

**Issue by kentindell** [Wren6991/Hazard3#25]
The parameter definition (in `hdl/hazard3_regfile_1w2r.v`) is:

`parameter W_ADDR = $clog2(W_DATA)`

That defines a 5 bit address width (which happens to be correct for the configuration), but shouldn't the parameter be:

`parameter W_ADDR = $clog2(N_REGS)`

**Comment by Wren6991** [comment]
Thanks, fixed on `develop`
