### ISSUE TITLE
hready_resp

### ISSUE THREAD

**Issue by laurentiuduca** [Wren6991/Hazard3#26]
hello, please tell me what meaning have the hready_resp signals, because i did not find it in the ahb or project docs

**Comment by Wren6991** [comment]
This is what is referred to as HREADYOUT in the AMBA specs. I use `_resp` to make the direction clearer (subordinate -> manager) because I find it confusing to have inputs called `xxx_out`

**Comment by Wren6991** [comment]
So, these (in AMBA 5 AHB  spec): 
![image](https://github.com/user-attachments/assets/54f5167d-54f0-4990-9de9-183064828e3b)

**Comment by laurentiuduca** [comment]
thank you
