### ISSUE TITLE
Nits: JTAGG -> JTAG

### ISSUE THREAD

**Issue by secworks** [Wren6991/Hazard3#9]
There is a minor spelling in the file: "JTAGG" should be "JTAG".

https://github.com/Wren6991/Hazard3/blob/e8b4578b4003d838f006dca00b5fea5852e4ab98/example_soc/fpga/fpga_ulx3s.f#L9C48-L9C53

**Comment by Wren6991** [comment]
Nope, that is the correct name of that ECP5 primitive

https://github.com/Wren6991/Hazard3/blob/e8b4578b4003d838f006dca00b5fea5852e4ab98/hdl/debug/dtm/hazard3_ecp5_jtag_dtm.v#L6

See notes here: https://github.com/tomverbeure/ecp5_jtag

**Comment by Wren6991** [comment]
It's a bit of an unfortunate name, but if you've already had JTAGA through JTAGF then what follows is inevitable.

**Comment by secworks** [comment]
Ah, my mistake, sorry.
